name: Push DockerHub Core
on:
  push:
    branches:
      - master
  release:
    types: [created]
jobs:
  node:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@a14471d838f6a7ce15cab8740f25e337c51e7cad
      - uses: ./actions/dockerhub/
        with:
          args: -f ./scripts/Dockerfile .
        env:
          DOCKER_NAMESPACE: neotracker
          DOCKER_IMAGE_NAME: core
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
